apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
spec:
  replicas: 1 # Number of Nginx container replicas to run
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
      - name: nginx-website
        image: my-nginx-website:latest # Use the image you built
        ports:
        - containerPort: 80 # Expose container port 80

