CREATE TABLE food_cart_permits (
  locationid INTEGER PRIMARY KEY,
  applicant VARCHAR(50),
  facility_type VARCHAR(20),
  cnn TEXT,
  location_description VARCHAR(100),
  address TEXT,
  blocklot TEXT,
  block INTEGER,
  lot INTEGER,
  permit TEXT,
  status TEXT,
  food_items TEXT,
  x DOUBLE,
  y DOUBLE,
  latitude DOUBLE,
  longitude DOUBLE,
  schedule VARCHAR(255),
  dayshours VARCHAR(50),
  noisent VARCHAR(10),
  approved VARCHAR(10),
  received DATE,
  prior_permit VARCHAR(20),
  expiration_date DATE,
  location VARCHAR(50),
  fire_prevention_districts VARCHAR(50),
  police_districts VARCHAR(50),
  supervisor_districts VARCHAR(50),
  zip_codes VARCHAR(50),
  neighborhoods_old VARCHAR(50)
);
